#' filename : visulize_sbt.R
#' Date : 2020-05-26
#' contributor : Yanshuo Chu
#' function: visulize doublet 's nfeature box plot

##libraries
suppressMessages({library(optparse)
library(Seurat)
library(ggplot2)
library(ggpubr)
library(rjson)
library(rlist)
library(dplyr)})
print('----QC----')
option_list = list(
    make_option(c("-d", "--data"),
                type = "character",
                default = NULL,
                help = "rds file generated by load-cellranger.r",
                metavar = 'character'),
    make_option(c("-o",'--out'),
                type = 'character',
                default = 'doublets-viability-plot.pdf',
                help = 'output file name for the plot [default = %default]',
                metavar = 'character'),
    make_option(c("-c",'--param'),
                type = 'character',
                help = 'json parameter file for plot figure size',
                metavar = 'character')
);

opt_parser = OptionParser(option_list = option_list);
opt = parse_args(opt_parser);

if(is.null(opt$data)) {
    print_help(opt_parser)
    stop("Input data must be provided", call. = F)
}

##load param
param <- fromJSON(file = opt$param)

##load data
print('loading data')
combined.data = readRDS(opt$data)
print('making plots')


gpdat = tidyr::gather(data.frame(rname = rownames(combined.data@meta.data),
                                 combined.data@meta.data),
                      key = type,
                      value = value, -rname, -orig.ident, -sbt_is_doublet, -sbt_doublet_score,
                      c('percent.mito', 'nFeature_RNA', 'nCount_RNA'))

temp.data <- filter(gpdat, type == c('percent.mito', 'nFeature_RNA', 'nCount_RNA'))

plot.sbtbox = ggplot(data = temp.data, aes(x = sbt_is_doublet, y=value))
plot.sbtbox = plot.sbtbox + geom_boxplot(aes(color=sbt_is_doublet)) + facet_grid(type ~ orig.ident, scales="free") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

pdf(opt$out)
print(plot.sbtbox)
dev.off()

print('----end----')
